repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files
      - id: debug-statements
      - id: name-tests-test
        args: [-- pytest-test-first]
      - id: requirements-txt-fixer

#  - repo: https://github.com/PyCQA/flake8
#    rev: 6.0.0
#    hooks:
#      - id: flake8
# logic to ignore line is too long

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.275
    hooks:
      - id: ruff
        args: [--fix]
